name = "Zag"
version = "0.1.0"
defaultTargets = ["zag"]

[[lean_lib]]
name = "Zag"

[[lean_lib]]
name = "Lib"
roots = ["Lib.Peano.Defs", "Lib.PeanoHeap"]

[[lean_lib]]
name = "Meta"
roots = ["Meta.Induction", "Meta.UnifyType"]

[[lean_lib]]
name = "Test"
roots = ["Test.Block", "Test.Exit", "Test.Gauss", "Test.Monad", "Test.Autocorres.Examples", "Test.AutoCorresExamples"]

[[lean_exe]]
name = "zag"
root = "Main"
