name = "Zag"
version = "0.1.0"
defaultTargets = ["zag"]

[[lean_lib]]
name = "Zag"

[[lean_lib]]
name = "Lib"
roots = ["Lib.Peano.Defs"]

[[lean_lib]]
name = "Meta"
roots = ["Meta.Induction"]

[[lean_lib]]
name = "Test"
roots = ["Test.Block", "Test.Gauss", "Test.Monad"]

[[lean_exe]]
name = "zag"
root = "Main"
