import Lang.AutoCorres.SimplConv

/-!
# Proof-producing SIMPL conversion

Corresponds only to [`tools/autocorres/simpl_conv.ML`](https://github.com/seL4/l4v/blob/bc2599a59c43e673dca021b10b9841e9b8da4430/tools/autocorres/simpl_conv.ML).

This is the structural SIMPL-to-L1 semantic conversion over the local command
core, corresponding to upstream `simpl_conv'`. The upstream procedure-table,
C-parser call pattern, definition, cleanup, and whole-program orchestration
machinery is not available in the local model.
-/

namespace Zag.Lang.AutoCorres.ML.SimplConv

universe u v w

open Zag.Lang.AutoCorres.SimplConv.Kernel

/-- SIMPL constructors for which the local converter has no sound L1 rule. -/
inductive UnsupportedConstructor where
  | Call
  | DynCom
  deriving DecidableEq, Repr

/-- A reviewable conversion failure, including its exact source constructor. -/
structure Unsupported where
  sourceConstructor : UnsupportedConstructor
  reason : String
  deriving DecidableEq, Repr

def unsupportedCall : Unsupported :=
  { sourceConstructor := .Call
    reason := "Call requires a proved callee correspondence and call-lowering rule" }

def unsupportedDynCom : Unsupported :=
  { sourceConstructor := .DynCom
    reason := "DynCom requires state-dependent command conversion" }

/--
The pure structural conversion corresponding to upstream `simpl_conv'`.
Its indexed input excludes unsupported source shapes before conversion begins.
-/
def simplConv (checkTermination : Bool)
    (env : Simpl.Body State Proc Fault) {source : Simpl.Com State Proc Fault}
    (supported : Supported source) : Certificate checkTermination env source :=
  match supported with
  | .skip =>
      { target := .skip
        corres := L1.L1Corres_skip checkTermination env }
  | .seq leftSupported rightSupported =>
      let leftCertificate := simplConv checkTermination env leftSupported
      let rightCertificate := simplConv checkTermination env rightSupported
      { target := .seq leftCertificate.target rightCertificate.target
        corres := L1.L1Corres_seq leftCertificate.corres rightCertificate.corres }
  | .basic transform =>
      { target := .modify transform
        corres := L1.L1Corres_modify checkTermination env transform }
  | .cond test thenSupported elseSupported =>
      let thenCertificate := simplConv checkTermination env thenSupported
      let elseCertificate := simplConv checkTermination env elseSupported
      { target := .condition test thenCertificate.target elseCertificate.target
        corres := L1.L1Corres_condition thenCertificate.corres elseCertificate.corres }
  | .catch bodySupported handlerSupported =>
      let bodyCertificate := simplConv checkTermination env bodySupported
      let handlerCertificate := simplConv checkTermination env handlerSupported
      { target := .catch bodyCertificate.target handlerCertificate.target
        corres := L1.L1Corres_catch bodyCertificate.corres handlerCertificate.corres }
  | .while test bodySupported =>
      let bodyCertificate := simplConv checkTermination env bodySupported
      { target := .while test bodyCertificate.target
        corres := L1.L1Corres_while bodyCertificate.corres }
  | .throw =>
      { target := .throw
        corres := L1.L1Corres_throw checkTermination env }
  | .guard fault test bodySupported =>
      let bodyCertificate := simplConv checkTermination env bodySupported
      { target := .seq (.guard test) bodyCertificate.target
        corres := L1.L1Corres_guard bodyCertificate.corres fault }
  | .spec relation =>
      { target := .spec relation
        corres := L1.L1Corres_spec checkTermination env relation }

private def executionMember (program : L1.L1Program State) (initial : State) :
    Simpl.XState State Fault → Prop
  | .normal post => (Except.ok (), post) ∈ (program initial).results
  | .abrupt post => (Except.error (), post) ∈ (program initial).results
  | .fault _ | .stuck => True

/-- Every witnessed finite SIMPL execution is present in the target generated by
`simplConv`. Unlike `L1Corres`, this positive direction needs no no-failure premise. -/
theorem execution_mem (checkTermination : Bool)
    (env : Simpl.Body State Proc Fault) {source : Simpl.Com State Proc Fault}
    (supported : Supported source) {state : State} {result : Simpl.XState State Fault}
    (execution : Simpl.Exec env source (.normal state) result) :
    executionMember (simplConv checkTermination env supported).target.denote state result := by
  generalize initialEq : Simpl.XState.normal state = initial at execution
  induction execution generalizing state with
  | skip =>
      rename_i current
      cases initialEq
      cases supported
      change (Except.ok (), current) = (Except.ok (), current)
      rfl
  | basic =>
      rename_i transform current
      cases initialEq
      cases supported
      exact ⟨(), transform current, rfl, rfl⟩
  | spec relationMember =>
      cases initialEq
      cases supported
      rw [show (simplConv checkTermination env (Supported.spec _)).target.denote =
        L1.spec _ by rfl]
      exact AutoCorres.mem_liftE.mpr
        ⟨relationMember, rfl⟩
  | throw =>
      rename_i current
      cases initialEq
      cases supported
      change (Except.error (), current) = (Except.error (), current)
      rfl
  | guard holds bodyExecution induction =>
      rename_i test body current result fault
      cases initialEq
      cases supported with
      | guard fault test bodySupported =>
          have bodyMember := induction bodySupported rfl
          cases result with
          | normal post =>
              change (Except.ok (), post) ∈
                (L1.seq (L1.guard test)
                  (simplConv checkTermination env bodySupported).target.denote current).results
              rw [L1.seq, AutoCorres.mem_bindE_ok]
              exact ⟨(), current, AutoCorres.mem_liftE.mpr
                (AutoCorres.mem_guard.mpr ⟨holds, rfl, rfl⟩), bodyMember⟩
          | abrupt post =>
              change (Except.error (), post) ∈
                (AutoCorres.bindE (L1.guard test)
                  (fun _ => (simplConv checkTermination env bodySupported).target.denote)
                  current).results
              change (Except.error (), post) ∈
                ((simplConv checkTermination env bodySupported).target.denote current).results
                at bodyMember
              exact ⟨Except.ok (), current,
                AutoCorres.mem_liftE.mpr
                  (AutoCorres.mem_guard.mpr ⟨holds, rfl, rfl⟩), bodyMember⟩
          | fault label => exact True.intro
          | stuck => exact True.intro
  | seq firstExecution secondExecution firstIH secondIH =>
      rename_i first current middle second result
      cases initialEq
      cases supported with
      | seq leftSupported rightSupported =>
          have leftMember := firstIH leftSupported rfl
          cases middle with
          | normal middle =>
              have rightMember := secondIH rightSupported rfl
              cases result with
              | normal post =>
                  change (Except.ok (), post) ∈
                    (L1.seq (simplConv checkTermination env leftSupported).target.denote
                      (simplConv checkTermination env rightSupported).target.denote current).results
                  exact AutoCorres.mem_bindE_ok.mpr
                    ⟨(), middle, leftMember, rightMember⟩
              | abrupt post =>
                  change (Except.error (), post) ∈
                    (AutoCorres.bindE
                      (simplConv checkTermination env leftSupported).target.denote
                      (fun _ => (simplConv checkTermination env rightSupported).target.denote)
                      current).results
                  exact ⟨Except.ok (), middle, leftMember, rightMember⟩
              | fault label => exact True.intro
              | stuck => exact True.intro
          | abrupt middle =>
              cases secondExecution
              change (Except.error (), middle) ∈
                (AutoCorres.bindE
                  (simplConv checkTermination env leftSupported).target.denote
                  (fun _ => (simplConv checkTermination env rightSupported).target.denote)
                  current).results
              exact ⟨Except.error (), middle, leftMember, rfl⟩
          | fault label => cases secondExecution; exact True.intro
          | stuck => cases secondExecution; exact True.intro
  | condTrue holds branch branchIH =>
      cases initialEq
      cases supported with
      | cond test thenSupported elseSupported =>
          simpa [executionMember, simplConv, L1.condition, holds] using
            branchIH thenSupported rfl
  | condFalse doesNotHold branch branchIH =>
      cases initialEq
      cases supported with
      | cond test thenSupported elseSupported =>
          simpa [executionMember, simplConv, L1.condition, doesNotHold] using
            branchIH elseSupported rfl
  | whileFalse doesNotHold =>
      rename_i test body current
      cases initialEq
      cases supported with
      | «while» test bodySupported =>
          change WhileResult _ _ (some (Except.ok (), current))
            (some (Except.ok (), current))
          exact .stop (by simpa using doesNotHold)
  | whileTrue holds bodyExecution restExecution bodyIH restIH =>
      rename_i test body current middle result
      cases initialEq
      cases supported with
      | «while» test bodySupported =>
          have bodyMember := bodyIH bodySupported rfl
          cases middle with
          | normal middle =>
              have restMember := restIH (Supported.while test bodySupported) rfl
              cases result with
              | normal post =>
                  change WhileResult _ _ (some (Except.ok (), current))
                    (some (Except.ok (), post))
                  exact .step holds bodyMember restMember
              | abrupt post =>
                  change WhileResult _ _ (some (Except.ok (), current))
                    (some (Except.error (), post))
                  exact .step holds bodyMember restMember
              | fault label => exact True.intro
              | stuck => exact True.intro
          | abrupt middle =>
              cases restExecution
              change WhileResult _ _ (some (Except.ok (), current))
                (some (Except.error (), middle))
              exact .step holds bodyMember (.stop not_false)
          | fault label => cases restExecution; exact True.intro
          | stuck => cases restExecution; exact True.intro
  | catchMatch bodyExecution handlerExecution bodyIH handlerIH =>
      rename_i body current thrown handler result
      cases initialEq
      cases supported with
      | «catch» bodySupported handlerSupported =>
          have bodyMember := bodyIH bodySupported rfl
          have handlerMember := handlerIH handlerSupported rfl
          cases result with
          | normal post => exact ⟨Except.error (), thrown, bodyMember, handlerMember⟩
          | abrupt post => exact ⟨Except.error (), thrown, bodyMember, handlerMember⟩
          | fault label => exact True.intro
          | stuck => exact True.intro
  | catchMiss bodyExecution notAbrupt bodyIH =>
      rename_i body current result handler
      cases initialEq
      cases supported with
      | «catch» bodySupported handlerSupported =>
          have bodyMember := bodyIH bodySupported rfl
          cases result with
          | normal post => exact ⟨Except.ok (), post, bodyMember, rfl⟩
          | abrupt post => exact False.elim (notAbrupt True.intro)
          | fault label => exact True.intro
          | stuck => exact True.intro
  | guardFault => cases initialEq; trivial
  | faultProp => cases initialEq
  | specStuck => cases initialEq; trivial
  | «call» => cases supported
  | callUndefined => cases supported
  | stuckProp => cases initialEq
  | dynCom => cases supported
  | abruptProp => cases initialEq

@[simp] theorem simplConv_transport_target
    (checkTermination : Bool) (env : Simpl.Body State Proc Fault)
    {left right : Simpl.Com State Proc Fault} (equality : left = right)
    (supported : Supported left) :
    (simplConv checkTermination env (supported.transport equality)).target =
      (simplConv checkTermination env supported).target := by
  cases equality
  rfl

/-- Convert environment-indexed syntax, consuming exact certificates at calls. -/
def simplConvProgram {checkTermination : Bool}
    {env : Simpl.Body State Proc Fault} {source : Simpl.Com State Proc Fault}
    (supported : ProgramSupported checkTermination env source) :
    Certificate checkTermination env source :=
  match supported with
  | .skip => { target := .skip, corres := L1.L1Corres_skip checkTermination env }
  | .seq left right =>
      let leftCertificate := simplConvProgram left
      let rightCertificate := simplConvProgram right
      { target := .seq leftCertificate.target rightCertificate.target
        corres := L1.L1Corres_seq leftCertificate.corres rightCertificate.corres }
  | .basic transform =>
      { target := .modify transform
        corres := L1.L1Corres_modify checkTermination env transform }
  | .cond test thenSupported elseSupported =>
      let thenCertificate := simplConvProgram thenSupported
      let elseCertificate := simplConvProgram elseSupported
      { target := .condition test thenCertificate.target elseCertificate.target
        corres := L1.L1Corres_condition thenCertificate.corres elseCertificate.corres }
  | .catch bodySupported handlerSupported =>
      let bodyCertificate := simplConvProgram bodySupported
      let handlerCertificate := simplConvProgram handlerSupported
      { target := .catch bodyCertificate.target handlerCertificate.target
        corres := L1.L1Corres_catch bodyCertificate.corres handlerCertificate.corres }
  | .while test bodySupported =>
      let bodyCertificate := simplConvProgram bodySupported
      { target := .while test bodyCertificate.target
        corres := L1.L1Corres_while bodyCertificate.corres }
  | .throw => { target := .throw, corres := L1.L1Corres_throw checkTermination env }
  | .guard fault test bodySupported =>
      let bodyCertificate := simplConvProgram bodySupported
      { target := .seq (.guard test) bodyCertificate.target
        corres := L1.L1Corres_guard bodyCertificate.corres fault }
  | .spec relation =>
      { target := .spec relation
        corres := L1.L1Corres_spec checkTermination env relation }
  | .call proc sourceBody targetBody defined corres =>
      { target := .call targetBody
        corres := L1.L1Corres_call defined corres }

/-- Recognize the supported input shape, retaining the first unsupported child. -/
def recognizeSupported :
    (source : Simpl.Com State Proc Fault) -> Except Unsupported (Supported source)
  | .Skip => .ok .skip
  | .Seq left right =>
      match recognizeSupported left with
      | .error unsupported => .error unsupported
      | .ok leftSupported =>
          match recognizeSupported right with
          | .error unsupported => .error unsupported
          | .ok rightSupported => .ok (.seq leftSupported rightSupported)
  | .Basic transform => .ok (.basic transform)
  | .Cond test thenCom elseCom =>
      match recognizeSupported thenCom with
      | .error unsupported => .error unsupported
      | .ok thenSupported =>
          match recognizeSupported elseCom with
          | .error unsupported => .error unsupported
          | .ok elseSupported => .ok (.cond test thenSupported elseSupported)
  | .Catch body handler =>
      match recognizeSupported body with
      | .error unsupported => .error unsupported
      | .ok bodySupported =>
          match recognizeSupported handler with
          | .error unsupported => .error unsupported
          | .ok handlerSupported => .ok (.catch bodySupported handlerSupported)
  | .While test body =>
      match recognizeSupported body with
      | .error unsupported => .error unsupported
      | .ok bodySupported => .ok (.while test bodySupported)
  | .Throw => .ok .throw
  | .Guard fault test body =>
      match recognizeSupported body with
      | .error unsupported => .error unsupported
      | .ok bodySupported => .ok (.guard fault test bodySupported)
  | .Spec relation => .ok (.spec relation)
  | .Call _ => .error unsupportedCall
  | .DynCom _ => .error unsupportedDynCom

/-- Recognize a command and run the proof-producing structural conversion. -/
def run (checkTermination : Bool) (env : Simpl.Body State Proc Fault)
    (source : Simpl.Com State Proc Fault) :
    Except Unsupported (Certificate checkTermination env source) :=
  (recognizeSupported source).map (simplConv checkTermination env)

/-!
Upstream `convert`, `define`, and top-level `translate` are later orchestration
stages and are not implemented by this local structural conversion.
-/

/-! ## Algorithm regression pins -/

theorem simplConv_skip_target (checkTermination : Bool)
    (env : Simpl.Body State Proc Fault) :
    (simplConv checkTermination env Supported.skip).target = (.skip : Target State) := by
  rfl

theorem simplConv_nested_target (checkTermination : Bool)
    (env : Simpl.Body State Proc Fault) (fault : Fault) (test : State -> Prop)
    (transform : State -> State) (relation : Simpl.StateRel State) :
    (simplConv checkTermination env
      (Supported.seq (Supported.guard fault test (Supported.basic transform))
        (Supported.catch Supported.throw (Supported.spec relation)))).target =
      .seq (.seq (.guard test) (.modify transform))
        (.catch .throw (.spec relation)) := by
  rfl

theorem recognizeSupported_nested (Proc : Type v) (fault : Fault) (test : State -> Prop)
    (transform : State -> State) (relation : Simpl.StateRel State) :
    let source : Simpl.Com State Proc Fault :=
      .Seq (.Guard fault test (.Basic transform)) (.Catch .Throw (.Spec relation))
    recognizeSupported source =
      .ok (Supported.seq (Supported.guard fault test (Supported.basic transform))
        (Supported.catch Supported.throw (Supported.spec relation))) := by
  rfl

theorem run_call_unsupported (checkTermination : Bool)
    (env : Simpl.Body State Proc Fault) (proc : Proc) :
    run checkTermination env (.Call proc) = .error unsupportedCall := by
  rfl

theorem run_dynCom_unsupported (checkTermination : Bool)
    (env : Simpl.Body State Proc Fault)
    (command : State -> Simpl.Com State Proc Fault) :
    run checkTermination env (.DynCom command) = .error unsupportedDynCom := by
  rfl

theorem recognizeSupported_first_unsupported (proc : Proc)
    (command : State -> Simpl.Com State Proc Fault) :
    recognizeSupported (Simpl.Com.Seq (.Call proc) (.DynCom command)) =
      .error unsupportedCall := by
  rfl

end Zag.Lang.AutoCorres.ML.SimplConv
