import Lang.AutoCorres.WordAbstract
import Lang.AutoCorres.L2

/-!
# Proof-producing word abstraction kernel

Corresponds only to [`tools/autocorres/word_abstract.ML`](https://github.com/seL4/l4v/blob/bc2599a59c43e673dca021b10b9841e9b8da4430/tools/autocorres/word_abstract.ML).

This is the guarded unsigned, local proof kernel of the upstream conversion.
It deliberately excludes calls, heap operations, signed words, bitwise
operations, casts, loops, specifications, unknown values, and recursion
guards. Those constructs are represented only at the recognition boundary and
are errors; neither identity rewriting nor `L2.fail` is used as a fallback.

Source and target terms have different type interpretations. In particular, a
source word is a `BitVec width`, while its target is a `Nat`. Function inputs
are represented by typed `arg` nodes. The current HOAS target continuations are
certified kernel closures, not yet the closed first-order bodies generated by
the upstream tool; their typing constrains explicit arguments but does not by
itself establish complete prevention of cross-capture. Program denotation is
noncomputable because L2 conditionals are noncomputable; recognition and
transformation are ordinary pure functions.
-/

namespace Zag.Lang.AutoCorres.ML.WordAbstract

open Zag.Lang.AutoCorres
open Zag.Lang.AutoCorres.WordAbstract
open Zag.Lang.AutoCorres.WordAbstract.Kernel

namespace Source

export Zag.Lang.AutoCorres.WordAbstract.Kernel.Source (Value asWord Expr Syntax)
export Zag.Lang.AutoCorres.WordAbstract.Kernel.Source.Expr (eval)
export Zag.Lang.AutoCorres.WordAbstract.Kernel.Source.Syntax (denote)

end Source

namespace Target

export Zag.Lang.AutoCorres.WordAbstract.Kernel.Target (Value asNat Expr maxFor Syntax)
export Zag.Lang.AutoCorres.WordAbstract.Kernel.Target.Expr (eval)
export Zag.Lang.AutoCorres.WordAbstract.Kernel.Target.Syntax (denote)

end Target

namespace TypeMap

export Zag.Lang.AutoCorres.WordAbstract.Kernel.TypeMap
  (abstract concretize sourceRoundTrip abstract_unit abstract_bool abstract_word)

end TypeMap

export Zag.Lang.AutoCorres.WordAbstract.Kernel (ValueType TypeMap typeMap Certificate)

universe u

/-- A transformed value expression, its generated guard, and its value proof. -/
structure ValueEvidence {Argument : ValueType} {State : Type u} {type : ValueType}
    (source : Source.Expr Argument State type) where
  target : Target.Expr Argument State type
  guard : Target.Value Argument -> State -> Prop
  related : forall concreteArgument state,
    abstract_val (guard ((typeMap Argument).abstract concreteArgument) state)
      (target.eval ((typeMap Argument).abstract concreteArgument) state)
      (typeMap type).abstract (source.eval concreteArgument state)

theorem ValueEvidence.proposition
    {source : Source.Expr Argument State .bool} (evidence : ValueEvidence source)
    (concreteArgument : Source.Value Argument) (state : State) :
    abstract_val (evidence.guard ((typeMap Argument).abstract concreteArgument) state)
      (evidence.target.eval ((typeMap Argument).abstract concreteArgument) state = true)
      id (source.eval concreteArgument state = true) := by
  unfold abstract_val
  intro generated
  have equality : evidence.target.eval
      ((typeMap Argument).abstract concreteArgument) state =
      source.eval concreteArgument state := by
    simpa only [TypeMap.abstract_bool] using
      evidence.related concreteArgument state generated
  apply propext
  rw [equality]
  exact Iff.rfl

namespace Expr

/--
Evidence for every recognized expression rule. Arithmetic and comparison nodes
store the exact operation theorem used by proof construction.
-/
inductive Supported {Argument : ValueType} {State : Type u} :
    Source.Expr Argument State type -> Type (u + 1) where
  | arg : Supported .arg
  | state (type : ValueType) (read : State -> Source.Value type) :
      Supported (.state type read)
  | unit : Supported .unit
  | bool (value : Bool) : Supported (.bool value)
  | word (width : Nat) (value : BitVec width) : Supported (.word width value)
  | add {left right : Source.Expr Argument State (.word width)} :
      Supported left -> Supported right ->
      abstract_binop (fun a b => a + b <= UWORD_MAX width)
        (BitVec.toNat : BitVec width -> Nat) (· + ·) (· + ·) ->
      Supported (.add left right)
  | sub {left right : Source.Expr Argument State (.word width)} :
      Supported left -> Supported right ->
      abstract_binop (fun a b => b <= a)
        (BitVec.toNat : BitVec width -> Nat) (· - ·) (· - ·) ->
      Supported (.sub left right)
  | ult {left right : Source.Expr Argument State (.word width)} :
      Supported left -> Supported right ->
      abstract_bool_binop (fun _ _ => True)
        (BitVec.toNat : BitVec width -> Nat)
        (fun a b => decide (a < b)) (fun a b => a.ult b) ->
      Supported (.ult left right)
  | ule {left right : Source.Expr Argument State (.word width)} :
      Supported left -> Supported right ->
      abstract_bool_binop (fun _ _ => True)
        (BitVec.toNat : BitVec width -> Nat)
        (fun a b => decide (a <= b)) (fun a b => decide (a <= b)) ->
      Supported (.ule left right)
  | eq {left right : Source.Expr Argument State (.word width)} :
      Supported left -> Supported right ->
      abstract_bool_binop (fun _ _ => True)
        (BitVec.toNat : BitVec width -> Nat)
        (fun a b => decide (a = b)) (fun a b => decide (a = b)) ->
      Supported (.eq left right)

/-- Recognition is complete for the deliberately small expression grammar. -/
def supported : (source : Source.Expr Argument State type) -> Supported source
  | .arg => .arg
  | .state type read => .state type read
  | .unit => .unit
  | .bool value => .bool value
  | .word width value => .word width value
  | .add left right => .add (supported left) (supported right)
      bitVec_abstract_binop_add
  | .sub left right => .sub (supported left) (supported right)
      bitVec_abstract_binop_sub
  | .ult left right => .ult (supported left) (supported right)
      bitVec_abstract_bool_binop_ult
  | .ule left right => .ule (supported left) (supported right)
      bitVec_abstract_bool_binop_le
  | .eq left right => .eq (supported left) (supported right)
      bitVec_abstract_bool_binop_eq

/-- Pure expression conversion with side-condition generation. -/
def transform : {source : Source.Expr Argument State type} ->
    Supported source -> ValueEvidence source
  | _, .arg =>
      { target := .arg
        guard := fun _ _ => True
        related := by intros; intro _; simp [Target.Expr.eval, Source.Expr.eval] }
  | _, .state type read =>
      { target := .state type fun state => (typeMap type).abstract (read state)
        guard := fun _ _ => True
        related := by intros; intro _; simp [Target.Expr.eval, Source.Expr.eval] }
  | _, .unit =>
      { target := .unit
        guard := fun _ _ => True
        related := by intros; intro _; simp [Target.Expr.eval, Source.Expr.eval] }
  | _, .bool value =>
      { target := .bool value
        guard := fun _ _ => True
        related := by intros; intro _; simp [Target.Expr.eval, Source.Expr.eval] }
  | _, .word width value =>
      { target := .word width value.toNat
        guard := fun _ _ => True
        related := by intros; intro _; simp [Target.Expr.eval, Source.Expr.eval] }
  | _, .add leftSupported rightSupported law =>
      let left := transform leftSupported
      let right := transform rightSupported
      { target := .add left.target right.target
        guard := fun argument state =>
          left.guard argument state /\ right.guard argument state /\
            Target.asNat (left.target.eval argument state) +
              Target.asNat (right.target.eval argument state) <=
              Target.maxFor left.target
        related := by
          intro concreteArgument state
          simpa [Target.asNat, Target.maxFor, Target.Expr.eval, Source.Expr.eval,
            Source.asWord, Target.Value, Source.Value, typeMap, TypeMap.abstract,
            valid_typ_abs_fn_bitVec] using
            abstract_expr_binop law (left.related concreteArgument state)
              (right.related concreteArgument state) }
  | _, .sub leftSupported rightSupported law =>
      let left := transform leftSupported
      let right := transform rightSupported
      { target := .sub left.target right.target
        guard := fun argument state =>
          left.guard argument state /\ right.guard argument state /\
            Target.asNat (right.target.eval argument state) <=
              Target.asNat (left.target.eval argument state)
        related := by
          intro concreteArgument state
          simpa [Target.asNat, Target.Expr.eval, Source.Expr.eval,
            Source.asWord, Target.Value, Source.Value, typeMap, TypeMap.abstract,
            valid_typ_abs_fn_bitVec] using
            abstract_expr_binop law (left.related concreteArgument state)
              (right.related concreteArgument state) }
  | _, .ult (left := sourceLeft) (right := sourceRight)
      leftSupported rightSupported law =>
      let left := transform leftSupported
      let right := transform rightSupported
      { target := .ult left.target right.target
        guard := fun argument state =>
          left.guard argument state /\ right.guard argument state /\ True
        related := by
          intro concreteArgument state
          unfold abstract_val
          rintro ⟨leftGuard, rightGuard, _⟩
          have leftEquality := left.related concreteArgument state leftGuard
          have rightEquality := right.related concreteArgument state rightGuard
          have operationEquality := law
            (Source.asWord (Source.Expr.eval concreteArgument state sourceLeft))
            (Source.asWord (Source.Expr.eval concreteArgument state sourceRight)) True.intro
          simp only [Target.Expr.eval, Source.Expr.eval, Target.asNat, Source.asWord,
            TypeMap.abstract_bool]
          rw [leftEquality, rightEquality]
          exact operationEquality.symm }
  | _, .ule (left := sourceLeft) (right := sourceRight)
      leftSupported rightSupported law =>
      let left := transform leftSupported
      let right := transform rightSupported
      { target := .ule left.target right.target
        guard := fun argument state =>
          left.guard argument state /\ right.guard argument state /\ True
        related := by
          intro concreteArgument state
          unfold abstract_val
          rintro ⟨leftGuard, rightGuard, _⟩
          have leftEquality := left.related concreteArgument state leftGuard
          have rightEquality := right.related concreteArgument state rightGuard
          have operationEquality := law
            (Source.asWord (Source.Expr.eval concreteArgument state sourceLeft))
            (Source.asWord (Source.Expr.eval concreteArgument state sourceRight)) True.intro
          simp only [Target.Expr.eval, Source.Expr.eval, Target.asNat, Source.asWord,
            TypeMap.abstract_bool]
          rw [leftEquality, rightEquality]
          exact operationEquality.symm }
  | _, .eq (left := sourceLeft) (right := sourceRight)
      leftSupported rightSupported law =>
      let left := transform leftSupported
      let right := transform rightSupported
      { target := .eq left.target right.target
        guard := fun argument state =>
          left.guard argument state /\ right.guard argument state /\ True
        related := by
          intro concreteArgument state
          unfold abstract_val
          rintro ⟨leftGuard, rightGuard, _⟩
          have leftEquality := left.related concreteArgument state leftGuard
          have rightEquality := right.related concreteArgument state rightGuard
          have operationEquality := law
            (Source.asWord (Source.Expr.eval concreteArgument state sourceLeft))
            (Source.asWord (Source.Expr.eval concreteArgument state sourceRight)) True.intro
          simp only [Target.Expr.eval, Source.Expr.eval, Target.asNat, Source.asWord,
            TypeMap.abstract_bool]
          rw [leftEquality, rightEquality]
          exact operationEquality.symm }

end Expr

/-- Indexed evidence that the entire program is in the certified fragment. -/
inductive Supported {Argument : ValueType} {State : Type u} :
    {exception result : ValueType} ->
      Source.Syntax Argument State exception result -> Type (u + 1) where
  | gets {exception result : ValueType} {value : Source.Expr Argument State result}
      (valueSupported : Expr.Supported value)
      (names : List String) : Supported (.gets value names)
  | guard {exception : ValueType} {test : Source.Expr Argument State .bool}
      (testSupported : Expr.Supported test) :
      Supported (.guard test)
  | seq {exception middle result : ValueType}
      {first : Source.Syntax Argument State exception middle} {next}
      (firstSupported : Supported first)
      (nextSupported : forall value : Source.Value middle, Supported (next value)) :
      Supported (.seq first next)
  | condition {exception result : ValueType} {test : Source.Expr Argument State .bool}
      {thenBranch elseBranch : Source.Syntax Argument State exception result}
      (testSupported : Expr.Supported test) (thenSupported : Supported thenBranch)
      (elseSupported : Supported elseBranch) :
      Supported (.condition test thenBranch elseBranch)
  | «catch» {exception caught result : ValueType}
      {body : Source.Syntax Argument State caught result} {handler}
      (bodySupported : Supported body)
      (handlerSupported : forall exception : Source.Value caught,
        Supported (handler exception)) : Supported (.catch body handler)
  | throw {exception result : ValueType} (value : Source.Value exception)
      (names : List String) : Supported (.throw value names)
  | skip {exception : ValueType} : Supported (.skip :
      Source.Syntax Argument State exception .unit)
  | fail {exception result : ValueType} : Supported (.fail :
      Source.Syntax Argument State exception result)

/-- Structural recognition for the source grammar. -/
def supported {Argument : ValueType} {State : Type u} {Exception Result : ValueType} :
    (source : Source.Syntax Argument State Exception Result) -> Supported source
  | .gets value names => .gets (exception := Exception) (Expr.supported value) names
  | .guard test => .guard (exception := Exception) (Expr.supported test)
  | .seq first next => .seq (exception := Exception) (result := Result)
      (supported first) fun value =>
      supported (next value)
  | .condition test thenBranch elseBranch =>
      .condition (exception := Exception) (Expr.supported test)
        (supported thenBranch) (supported elseBranch)
  | .catch body handler =>
      .catch (exception := Exception) (supported body) fun exception =>
        supported (handler exception)
  | .throw exception names => .throw (result := Result) exception names
  | .skip => .skip
  | .fail => .fail

/-- Local precursor: its precondition is inserted as a guard by its parent. -/
private structure RawCertificate {Argument : ValueType} {State : Type u}
    {Exception Result : ValueType}
    (source : Source.Syntax Argument State Exception Result) where
  target : Target.Syntax Argument State Exception Result
  required : Target.Value Argument -> State -> Prop
  corres : forall concreteArgument,
    corresTA (required ((typeMap Argument).abstract concreteArgument))
      (typeMap Result).abstract (typeMap Exception).abstract
      (target.denote ((typeMap Argument).abstract concreteArgument))
      (source.denote concreteArgument)

private def transformRaw {Argument : ValueType} {State : Type u}
    {Exception Result : ValueType} :
    (source : Source.Syntax Argument State Exception Result) -> RawCertificate source
  | .gets sourceValue names =>
      let value := Expr.transform (Expr.supported sourceValue)
      { target := .gets value.target names
        required := value.guard
        corres := by
          intro concreteArgument
          exact corresTA_L2_gets (value.related concreteArgument) }
  | .guard sourceTest =>
      let test := Expr.transform (Expr.supported sourceTest)
      { target := .guard fun argument state =>
          test.target.eval argument state = true /\ test.guard argument state
        required := fun _ _ => True
        corres := by
          intro concreteArgument
          apply corresTA_L2_guard
          exact test.proposition concreteArgument }
  | .seq firstSource sourceNext =>
      let first := transformRaw firstSource
      let nextTarget := fun value =>
        (transformRaw (sourceNext ((typeMap _).concretize value))).target
      let nextRequired := fun value =>
        (transformRaw (sourceNext ((typeMap _).concretize value))).required
      { target := .seq first.target fun value =>
          .seq (.guard (nextRequired value)) fun _ => nextTarget value
        required := first.required
        corres := by
          intro concreteArgument
          apply corresTA_L2_seq (first.corres concreteArgument)
          intro value
          have valueEquality := (typeMap _).sourceRoundTrip value
          have targetEquality : nextTarget ((typeMap _).abstract value) =
              (transformRaw (sourceNext value)).target := by
            simp only [nextTarget]
            rw [valueEquality]
          have requiredEquality : nextRequired ((typeMap _).abstract value) =
              (transformRaw (sourceNext value)).required := by
            simp only [nextRequired]
            rw [valueEquality]
          rw [targetEquality, requiredEquality]
          exact (transformRaw (sourceNext value)).corres concreteArgument }
  | .condition sourceTest thenSource elseSource =>
      let test := Expr.transform (Expr.supported sourceTest)
      let thenResult := transformRaw thenSource
      let elseResult := transformRaw elseSource
      { target := .condition test.target
          (.seq (.guard thenResult.required) fun _ => thenResult.target)
          (.seq (.guard elseResult.required) fun _ => elseResult.target)
        required := test.guard
        corres := by
          intro concreteArgument
          apply corresTA_L2_condition
            (thenResult.corres concreteArgument) (elseResult.corres concreteArgument)
          exact test.proposition concreteArgument }
  | .catch bodySource sourceHandler =>
      let body := transformRaw bodySource
      let handlerTarget := fun exception =>
        (transformRaw (sourceHandler ((typeMap _).concretize exception))).target
      let handlerRequired := fun exception =>
        (transformRaw (sourceHandler ((typeMap _).concretize exception))).required
      { target := .catch body.target fun exception =>
          .seq (.guard (handlerRequired exception)) fun _ => handlerTarget exception
        required := body.required
        corres := by
          intro concreteArgument
          apply corresTA_L2_catch (body.corres concreteArgument)
          intro exception
          have valueEquality := (typeMap _).sourceRoundTrip exception
          have targetEquality : handlerTarget ((typeMap _).abstract exception) =
              (transformRaw (sourceHandler exception)).target := by
            simp only [handlerTarget]
            rw [valueEquality]
          have requiredEquality : handlerRequired ((typeMap _).abstract exception) =
              (transformRaw (sourceHandler exception)).required := by
            simp only [handlerRequired]
            rw [valueEquality]
          rw [targetEquality, requiredEquality]
          exact (transformRaw (sourceHandler exception)).corres concreteArgument }
  | .throw value names =>
      { target := .throw ((typeMap _).abstract value) names
        required := fun _ _ => True
        corres := by
          intro concreteArgument
          exact corresTA_L2_throw (abstract_val_trivial _ value) }
  | .skip =>
      { target := .skip
        required := fun _ _ => True
        corres := fun _ => corresTA_L2_skip }
  | .fail =>
      { target := .fail
        required := fun _ _ => True
        corres := fun _ => corresTA_L2_fail }

/-- Total ordinary pure transformation over `Supported` evidence. -/
def transform {Argument : ValueType} {State : Type u} {Exception Result : ValueType}
    {source : Source.Syntax Argument State Exception Result}
    (_evidence : Supported source) : Certificate source :=
  let raw := transformRaw source
  { target := .seq (.guard raw.required) fun _ => raw.target
    corres := fun concreteArgument =>
      corresTA_precond_to_guard (raw.corres concreteArgument) }

/-- Source-total pass interface for the restricted grammar. -/
def transformSource {Argument : ValueType} {State : Type u}
    {Exception Result : ValueType}
    (source : Source.Syntax Argument State Exception Result) : Certificate source :=
  transform (supported source)

/--
A certified HOAS function boundary over an abstract argument. Its target is a
kernel closure, not yet an upstream-style closed first-order generated body.
-/
structure FunctionCertificate {Argument : ValueType} {State : Type u}
    {Exception Result : ValueType}
    (source : Source.Syntax Argument State Exception Result) where
  target : Target.Syntax Argument State Exception Result
  corres : forall concreteArgument,
    corresTA (fun _ => True) (typeMap Result).abstract (typeMap Exception).abstract
      (target.denote ((typeMap Argument).abstract concreteArgument))
      (source.denote concreteArgument)

def transformFunction {Argument : ValueType} {State : Type u}
    {Exception Result : ValueType}
    {source : Source.Syntax Argument State Exception Result}
    (evidence : Supported source) : FunctionCertificate source :=
  let certificate := transform evidence
  { target := certificate.target
    corres := certificate.corres }

/-- Categories intentionally rejected by this local kernel. -/
inductive UnsupportedCategory where
  | signedArithmetic
  | bitwise
  | call
  | heap
  | cast
  | loop
  | specification
  | unknown
  | recursionGuard
  deriving DecidableEq, Repr

/--
An unsupported reified source node. Every constructor retains its source-node
identity and the category-specific payload needed to report what was rejected.
-/
inductive RecognitionError where
  | signedArithmetic (identity operation : String) (width : Nat)
  | bitwise (identity operation : String) (width : Nat)
  | call (identity callee : String)
  | heap (identity access : String)
  | cast (identity : String) (sourceWidth targetWidth : Nat)
  | loop (identity loopKind : String)
  | specification (identity specificationName : String)
  | unknown (identity renderedSyntax : String)
  | recursionGuard (identity functionName : String)
  deriving DecidableEq, Repr

/--
The actual reified recognition boundary. A certified `Source.Syntax` is one
case; unsupported source nodes are distinct constructors rather than a
caller-supplied category unrelated to the input.
-/
inductive Input (Argument : ValueType) (State : Type u)
    (Exception Result : ValueType) where
  | syntax (source : Source.Syntax Argument State Exception Result)
  | signedArithmetic (identity operation : String) (width : Nat)
  | bitwise (identity operation : String) (width : Nat)
  | call (identity callee : String)
  | heap (identity access : String)
  | cast (identity : String) (sourceWidth targetWidth : Nat)
  | loop (identity loopKind : String)
  | specification (identity specificationName : String)
  | unknown (identity renderedSyntax : String)
  | recursionGuard (identity functionName : String)

def unsupportedReason : UnsupportedCategory -> String
  | .signedArithmetic => "signed abstraction requires a certified BitVec/Int model"
  | .bitwise => "bitwise abstraction has no rule in the guarded unsigned kernel"
  | .call => "calls require a separately certified callee boundary"
  | .heap => "heap expressions require heap-lift getter rules"
  | .cast => "casts require width-specific conversion rules"
  | .loop => "loop conversion requires an invariant and monotonicity certificate"
  | .specification => "specifications require relation abstraction rules"
  | .unknown => "unknown values have no deterministic abstraction rule"
  | .recursionGuard => "recursion guards require the function-group kernel"

def RecognitionError.category : RecognitionError -> UnsupportedCategory
  | .signedArithmetic .. => .signedArithmetic
  | .bitwise .. => .bitwise
  | .call .. => .call
  | .heap .. => .heap
  | .cast .. => .cast
  | .loop .. => .loop
  | .specification .. => .specification
  | .unknown .. => .unknown
  | .recursionGuard .. => .recursionGuard

def RecognitionError.reason (error : RecognitionError) : String :=
  unsupportedReason error.category

/-- A source term dependently paired with evidence accepted by the kernel. -/
structure RecognizedInput (Argument : ValueType) (State : Type u)
    (Exception Result : ValueType) where
  source : Source.Syntax Argument State Exception Result
  evidence : Supported source

/-- Feed recognized evidence to the existing pure certified transformation. -/
def RecognizedInput.certificate
    {Argument : ValueType} {State : Type u} {Exception Result : ValueType}
    (input : RecognizedInput Argument State Exception Result) :
    Certificate input.source :=
  transform input.evidence

/-- Unsupported input is an error, never an identity rewrite or target failure. -/
def recognize {Argument : ValueType} {State : Type u} {Exception Result : ValueType}
    (input : Input Argument State Exception Result) :
    Except RecognitionError (RecognizedInput Argument State Exception Result) :=
  match input with
  | .syntax source => .ok { source, evidence := supported source }
  | .signedArithmetic identity operation width =>
      .error (.signedArithmetic identity operation width)
  | .bitwise identity operation width => .error (.bitwise identity operation width)
  | .call identity callee => .error (.call identity callee)
  | .heap identity access => .error (.heap identity access)
  | .cast identity sourceWidth targetWidth =>
      .error (.cast identity sourceWidth targetWidth)
  | .loop identity loopKind => .error (.loop identity loopKind)
  | .specification identity specificationName =>
      .error (.specification identity specificationName)
  | .unknown identity renderedSyntax => .error (.unknown identity renderedSyntax)
  | .recursionGuard identity functionName =>
      .error (.recursionGuard identity functionName)

/-! ## Reduction and semantic pins -/

private abbrev PinArgument := ValueType.unit
private abbrev PinState := Unit
private abbrev PinException := ValueType.unit

private def word8 (value : Nat) : Source.Expr PinArgument PinState (.word 8) :=
  .word 8 (BitVec.ofNat 8 value)

private def addProgram (left right : Nat) :
    Source.Syntax PinArgument PinState PinException (.word 8) :=
  .gets (.add (word8 left) (word8 right)) []

private def subExpr : Source.Expr PinArgument PinState (.word 8) :=
  .sub (word8 19) (word8 7)

private def comparisonExpr : Source.Expr PinArgument PinState .bool :=
  .ult (word8 7) (word8 19)

private def nestedProgram :
    Source.Syntax PinArgument PinState PinException .unit :=
  .seq .skip fun _ =>
    .condition (.ult (word8 7) (word8 20)) .skip .fail

/-- Each error is determined by the actual unsupported reified input node. -/
theorem unsupportedInputRecognitionPins :
    recognize (Input.signedArithmetic "signed#1" "add" 32 :
      Input PinArgument PinState PinException .unit) =
        .error (.signedArithmetic "signed#1" "add" 32) /\
    recognize (Input.bitwise "bitwise#2" "and" 32 :
      Input PinArgument PinState PinException .unit) =
        .error (.bitwise "bitwise#2" "and" 32) /\
    recognize (Input.call "call#3" "callee" :
      Input PinArgument PinState PinException .unit) =
        .error (.call "call#3" "callee") /\
    recognize (Input.heap "heap#4" "field" :
      Input PinArgument PinState PinException .unit) =
        .error (.heap "heap#4" "field") /\
    recognize (Input.cast "cast#5" 32 64 :
      Input PinArgument PinState PinException .unit) =
        .error (.cast "cast#5" 32 64) /\
    recognize (Input.loop "loop#6" "while" :
      Input PinArgument PinState PinException .unit) =
        .error (.loop "loop#6" "while") /\
    recognize (Input.specification "spec#7" "relation" :
      Input PinArgument PinState PinException .unit) =
        .error (.specification "spec#7" "relation") /\
    recognize (Input.unknown "unknown#8" "opaque term" :
      Input PinArgument PinState PinException .unit) =
        .error (.unknown "unknown#8" "opaque term") /\
    recognize (Input.recursionGuard "recguard#9" "recursiveFunction" :
      Input PinArgument PinState PinException .unit) =
        .error (.recursionGuard "recguard#9" "recursiveFunction") := by
  simp [recognize]

/-- A recognized in-range addition flows through the existing transformation. -/
theorem inRangeAddGuardPin :
    let input : Input PinArgument PinState PinException (.word 8) :=
      .syntax (addProgram 7 9)
    match recognize input with
    | .ok recognized =>
        match recognized.certificate.target with
        | .seq (.guard guard) _ => guard () () <-> 7 + 9 <= UWORD_MAX 8
        | _ => False
    | .error _ => False := by
  simp [recognize, RecognizedInput.certificate, transform, transformRaw,
    addProgram, word8, Expr.supported, Expr.transform, Target.Expr.eval,
    Target.asNat, Target.maxFor, UWORD_MAX]

/-- Subtraction reduces to unbounded Nat subtraction under its generated guard. -/
theorem subtractionReductionPin :
    let evidence := Expr.transform (Expr.supported subExpr)
    evidence.target.eval () () = 19 - 7 /\ evidence.guard () () := by
  simp [subExpr, word8, Expr.supported, Expr.transform, Target.Expr.eval,
    Target.asNat]

/-- Unsigned comparison reduces to the corresponding Nat comparison. -/
theorem comparisonReductionPin :
    let evidence := Expr.transform (Expr.supported comparisonExpr)
    evidence.target.eval () () = true /\ evidence.guard () () := by
  simp [comparisonExpr, word8, Expr.supported, Expr.transform, Target.Expr.eval,
    Target.asNat]

/-- Sequence and condition conversion retain guards before both continuations. -/
theorem nestedSequenceConditionPin :
    let certificate := transform (supported nestedProgram)
    match certificate.target with
    | .seq (.guard _) outerNext =>
        match outerNext () with
        | .seq .skip continuation =>
            match continuation () with
            | .seq (.guard _) afterGuard =>
                match afterGuard () with
                | .condition _ (.seq (.guard _) _) (.seq (.guard _) _) => True
                | _ => False
            | _ => False
        | _ => False
    | _ => False := by
  simp [transform, transformRaw, nestedProgram, Expr.supported,
    Expr.transform]

/-- Overflow is an executable target failure, not a correspondence assumption. -/
theorem overflowTargetFailurePin :
    ((transform (supported (addProgram 250 10))).target.denote () ()).failed := by
  simp [transform, transformRaw, addProgram, word8, Expr.supported,
    Expr.transform, Target.Syntax.denote, Target.Expr.eval, Target.asNat,
    Target.maxFor, L2.seq, L2.guard, bindE, L2.failed_liftE,
    AutoCorres.guard, UWORD_MAX]

end Zag.Lang.AutoCorres.ML.WordAbstract
